export const ipcChannels = {
  appGetStatus: 'app:get-status',
  appGetActions: 'app:get-actions',
  appGetProcessMetrics: 'app:get-process-metrics',
  operationGet: 'operation:get',
  steamCmdGetStatus: 'steamcmd:get-status',
  steamCmdInstall: 'steamcmd:install',
  serverGetInstallationStatus: 'server:get-installation-status',
  serverInstall: 'server:install',
  serverUpdate: 'server:update',
  serverStart: 'server:start',
  serverStop: 'server:stop',
  serverGetRuntimeStatus: 'server:get-runtime-status',
  serverGetQueryPortStatus: 'server:get-query-port-status',
  serverStopQueryPortOwner: 'server:stop-query-port-owner',
  playersGetStatus: 'players:get-status',
  adminGetStatus: 'admin:get-status',
  adminExecuteAction: 'admin:execute-action',
  configRead: 'config:read',
  configValidate: 'config:validate',
  configSave: 'config:save',
  configCreateDefault: 'config:create-default',
  configRestoreDefault: 'config:restore-default',
  firewallGetStatus: 'firewall:get-status',
  firewallCreateRule: 'firewall:create-rule',
  networkGetLocalAddresses: 'network:get-local-addresses',
  networkGetPublicAddress: 'network:get-public-address',
  backupGetSummary: 'backup:get-summary',
  backupCreateConfiguration: 'backup:create-configuration',
  backupCreateWorld: 'backup:create-world',
  backupRestore: 'backup:restore',
  backupDelete: 'backup:delete',
  logsGetRecent: 'logs:get-recent',
  windowMinimize: 'window:minimize',
  windowToggleMaximize: 'window:toggle-maximize',
  windowClose: 'window:close'
} as const;

export type IpcChannel = (typeof ipcChannels)[keyof typeof ipcChannels];
